name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: my-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p dist
          echo "Hello world build $(date)" > dist/myapp.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
